const ActionType ={
    USER_SIGNUP_REQ:"USER_SIGNUP_REQ",
    USER_SIGNUP_SUCCESS:"USER_SIGNUP_SUCCESS",
    USER_SIGNUP_ERROR:"USER_SIGNUP_ERROR",
    USER_SIGNUP_EMPTY:"USER_SIGNUP_EMPTY",
}

module.exports = ActionType